
name: My Workflow
on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: My Custom Action
        uses: ./action.yml
        with:
          input1: 'value1'
          input2: 'value2'

