---
name: CICD for node
'on':
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
        - 14.x
    steps:
    - uses: actions/checkout@v2
    - name: use node js
      uses: actions/setup-node@v1
      with:
        node-verson: "${{ matrix.node-version }}"
    - name: npm install and build
      run: |
        npm install
        npm run build
      env:
        CI: true
  deploy:
    needs:
    - build
    runs-on: ubuntu-latest
  steps:
  - name: SSH deploy
    uses: sharapesala/student-app@master
    with:
      host: "${{ secrets.HOST }}"
      username: "${{ secrets.USER }}"
      key: "${{ secrets.KEY }}"
      port: "${{ secrets.PORT }}"
      script: "curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh
        | bash\nnvm install 14\nnpm install -g pm2\ncd ~/CICD\ngit pull origin main\nnpm
        install\nnpm run build\npm2 restart api                    \n"
